# Generated by Django 5.2.7 on 2025-10-16 19:16

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Contenu')),
            ],
        ),
    ]
