# Generated by Django 5.2.7 on 2025-10-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='titre',
            field=models.CharField(default='', max_length=200),
        ),
    ]
