# Generated by Django 5.2.7 on 2025-10-22 09:16

import django_summernote.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mission_titre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='contenu',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
