# Generated by Django 5.2.8 on 2025-11-15 17:50

import django_summernote.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categorieequipe_initiative_instance_poste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', django_summernote.fields.SummernoteTextField()),
            ],
        ),
    ]
